Traceback (most recent call last):
  File "/Users/blankr/Desktop/pokemon/pokemon_ai/showdownai/browser.py", line 273, in switch_initial
    choose = self.driver.find_elements_by_name("chooseTeamPreview")[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "showdown.py", line 325, in run
    self.play_game(challenge=challenge)
  File "showdown.py", line 280, in play_game
    self.selenium.switch_initial(0, 0)
  File "/Users/blankr/Desktop/pokemon/pokemon_ai/showdownai/browser.py", line 276, in switch_initial
    choose = self.driver.find_elements_by_name("chooseTeamPreview")[index]
IndexError: list index out of range
