Traceback (most recent call last):
  File "showdown.py", line 315, in run
    self.play_game(challenge=challenge)
  File "showdown.py", line 282, in play_game
    move = self.agent.get_action(gamestate, 0)
  File "/Users/blankr/Desktop/pokemon/pokemon_ai/showdownai/agent.py", line 167, in get_action
    actions[0] = action
IndexError: list assignment index out of range
